spring:
  application:
    name: springtx
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG

    # JPA log
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.resource.transaction: DEBUG

    # JPA SQL
    org.hibernate.SQL: DEBUG
